KH-184: HC screening - Add Foot exam question
openmrs/ozone-distro-cambodia pull request #113
Opened 2023-05-05 12:06 UTC by kdaud

Refer to [KH-184](https://issues.openmrs.org/browse/KH-184)

2023-05-05 14:03 UTC, kdaud commented
[Screening.webm](https://user-images.githubusercontent.com/38831673/236479706-e0622334-2d44-42de-9065-1845b4b1cf9a.webm)

2023-05-07 02:45 UTC, kdaud commented
[Screening.webm](https://user-images.githubusercontent.com/38831673/236654945-ffe745b3-e251-45ae-adc2-71777a63aa57.webm)

2023-05-07 15:03 UTC, kazlaw approved these changes
Looks good, ready for merging @rbuisson

2023-05-09 09:28 UTC, rbuisson requested changes

2023-05-09 09:41 UTC, rbuisson approved these changes

2023-05-09 09:41 UTC, merged